from langchain import OpenAI, ConversationChain
from langchain.prompts import PromptTemplate
from langchain.llms import HuggingFaceHub

class TextQuestionAnswering:
    def __init__(self, repo_id="EleutherAI/gpt-neo-2.7B", verbose=True):
        """
        Initializes the TextQuestionAnswering class with a language model from HuggingFaceHub.

        Args:
            repo_id (str): The repository ID for the language model to be used.
            verbose (bool): Whether to print verbose information during conversation.
        """
        self.llm = HuggingFaceHub(repo_id=repo_id)
        self.conversation = ConversationChain(llm=self.llm, verbose=verbose)

    def generate_prompt(self, context, question):
        """
        Generates a prompt by combining the given context and question.

        Args:
            context (str): The input text over which the question is asked.
            question (str): The question to be asked about the context.

        Returns:
            str: The combined prompt to be used for prediction.
        """
        return f"{context}\n\nPregunta: {question}\nRespuesta:"

    def ask_question(self, context, question):
        """
        Asks a question based on the given context and returns the model's response.

        Args:
            context (str): The input text over which the question is asked.
            question (str): The question to be asked about the context.

        Returns:
            str: The response generated by the language model.
        """
        prompt = self.generate_prompt(context, question)
        response = self.conversation.predict(prompt=prompt)
        return response

if __name__ == "__main__":
    # Define the context and question
    context = "El texto de entrada sobre el que deseas hacer preguntas."
    question = "¿Cuál es la idea principal del texto?"

    # Create an instance of TextQuestionAnswering and ask a question
    tqa = TextQuestionAnswering()
    response = tqa.ask_question(context, question)

    # Print the response
    print(response)
